fix missing module to install (#1110)
lasso module is missing

CLI installation globally is not enough, otherwise I get this error:
Error while applying option of "plugin". 
Cause: Error: Cannot find module 'lasso/package'